config/routes.rb
Rails.application.routes.draw do
  
  root to: 'public/homes#top'
  get "search" => "searches#search"
  devise_for :admins, skip: [:registrations, :passwords]  ,controllers: {
    sessions: "admin/sessions"
  }

  #get 'maps/index'
  #root to: 'maps#index'
  #resources :maps, only: [:index]

#  devise_for :users,skip: [:passwords], controllers: {
#    registrations: "public/registrations",
#    sessions: "public/sessions"
#  }
  devise_for :users, skip: [:registrations, :passwords], controllers: {
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in', as:'guest_sign_in'
    get '/users/sign_up' => 'public/registrations#new', as: 'new_user_registration'
    post '/users' => 'public/registrations#create', as: 'user_registration'
  end

  scope module: :public do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :friends
    resources :plans
    get 'users/my_page' => 'users#show'
    get 'users/edit' => 'users#edit'
    get 'users/confirm' => 'users#confirm'
    patch 'users/info' => 'users#update'
    patch 'users/quit' => 'users#quit'
    get 'plans/:id/get' => 'plans#plan_get'
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :topics
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  has_one_attached :image
  
  #def get_image
    #unless image.attached?
      #file_path = Rails.root.join('app/assets/images/no_image.jpg')
    #end
     # image
  #end
  
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController
  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to admin_topics_path
    else
      render:new
    end
  end

  def index
     @topics  = Topic.page(params[:page]).per(5)
  end

  def edit
    @topic = Topic.find(params[:id])


  end

  def show
    @topic = Topic.find(params[:id])
  end

  def update
    topic = Topic.find(params[:id])
    topic.update(topic_params)
    redirect_to admin_topic_path(topic.id)
  end

 def destroy
   topic =Topic.find(params[:id])
   topic.destroy
   redirect_to admin_topics_path
 end

 private
 def topic_params
   params.require(:topic).permit(:category, :title, :article, :image)
 end
end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/views/admin/topics/edit.html.erb
<div class="container">
  <div class="row my-4">
    <h2 class="col-3 mb-5 offset-3">トピック編集</h2>
    <div class="col-3"><%= link_to '削除', admin_topic_path(@topic.id), method: :delete, class: "btn btn-danger" %></div>
  </div>
  
  <%= form_with model: @topic, url: admin_topic_path, method: :patch do |f| %>
  
  <div class="row my-3">
    <div class="col-lg-2 offset-3"><%= f.label :カテゴリ %></div>
    <div class="col-5"><%= f.text_field :category %></div>
  </div>
  
  <div class="row my-3">
    <div class="col-lg-2 offset-3"><%= f.label :タイトル %></div>
    <div class="col-lg-5"><%= f.text_field :title %></div>
  </div>
  
  <div class="row my-3">
    <div class="col-lg-2 offset-3"><%= f.label :内容 %></div>
    <div class="col-lg-5"><%= f.text_area :article %></div>
  </div>
  
  <div class="row my-3">
    <div class="col-lg-2 offset-3"><%= f.label :写真イメージ %></div>
    <div class="col-lg-5"><%= f.file_field :image %></div>
  </div>
  
  <div class="row my-4">
    <div class="col-lg-4 offset-5"><%= f.submit "変更内容を保存", class: "btn btn-success" %></div>
  </div>
  <% end %>
</div>

app/views/admin/topics/index.html.erb
<div class="container">
  <div class="row my-4">
    <h2 class="col-lg-3 mb-5 offset-3">連絡事項</h2>
    <div class="col-lg-2"><%= link_to "+", new_admin_topic_path, class: "btn btn-secondary" %></div>
  </div>
  
  <% @topics.each do |topic| %>
  <%= link_to admin_topic_path(topic) do %>
  
  <div class="row my-3">
    <div class="col-1 offset-3"><%= topic.created_at.strftime("%Y") %></div>
    <div class="col-1"><%= topic.created_at.strftime("%m/%d") %></div>
    <div class="col-5"><%= topic.title %></div>
  </div>
   <% end %>
   <% end %>
   
  <div class="row my-3">
     <div class="col-5 offset-5"><%= paginate @topics %></div>
   </div>
</div>

app/views/admin/topics/new.html.erb
<div class="container">
  <div class="row my-4">
    <h2 class="col-3 mb-5 offset-2">トピック作成</h2>
  </div>
  <%= form_with model: @topic, url: admin_topics_path do |f| %>
  <div class="row my-3">
    <div class="col-3 offset-3"><%= f.label :カテゴリ %></div>
    <div class="col-5"><%= f.text_field :category %></div>
  </div>

  <div class="row my-3">
    <div class="col-3 offset-3"><%= f.label :タイトル %></div>
    <div class="col-5"><%= f.text_field :title %></div>
  </div>

  <div class="row my-3">
    <div class="col-3 offset-3"><%= f.label :内容 %></div>
    <div class="col-5"><%= f.text_area :article %></div>
  </div>

  <div class="row my-3">
    <div class="col-3 offset-3"><%= f.label :写真イメージ%></div>
    <div class="col-5"><%= f.file_field :image %></div>
  </div>

  <div class="row my-4">
    <div class="col-4 offset-5"><%= f.submit "作成", class: "btn btn-primary" %></div>
  </div>
  <% end %>
</div>

app/views/admin/topics/show.html.erb
<div class="container">
  <div class="row my-4">
    <h2 class="col-3 mb-5 offset-3">トピック詳細</h2>
    <div class="col-2"><%= link_to '編集', edit_admin_topic_path, class: "btn btn-success" %></div>
  </div>

  <div class="row my-3">
    <div class="col-2 offset-1">
      <% if @topic.image.attached? %>
        <%= image_tag @topic.image, size: "200x200" %>
      <% else %>
        <%= image_tag 'no_image.jpg', size:"200x200" %>
      <% end %>
    </div>

    <div class="col-8 offset-1">
      <table class="table">
        <thead>
          <tr>
            <th>カテゴリ</th>
            <th><%= @topic.category %></th>
          </tr>

          <tr>
            <th>タイトル</th>
            <th><%= @topic.title %></th>
          </tr>

          <tr>
            <th>内容</th>
            <th><%= @topic.article %></th>
          </tr>
        </thead>
      </table>
    </div>
  </div>
</div>