config/routes.rb
Rails.application.routes.draw do
  
  root to: 'public/homes#top'
  get "search" => "searches#search"
  devise_for :admins, skip: [:registrations, :passwords]  ,controllers: {
    sessions: "admin/sessions"
  }

  #get 'maps/index'
  #root to: 'maps#index'
  #resources :maps, only: [:index]

#  devise_for :users,skip: [:passwords], controllers: {
#    registrations: "public/registrations",
#    sessions: "public/sessions"
#  }
  devise_for :users, skip: [:registrations, :passwords], controllers: {
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in', as:'guest_sign_in'
    get '/users/sign_up' => 'public/registrations#new', as: 'new_user_registration'
    post '/users' => 'public/registrations#create', as: 'user_registration'
  end

  scope module: :public do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :friends
    resources :plans
    get 'users/my_page' => 'users#show'
    get 'users/edit' => 'users#edit'
    get 'users/confirm' => 'users#confirm'
    patch 'users/info' => 'users#update'
    patch 'users/quit' => 'users#quit'
    get 'plans/:id/get' => 'plans#plan_get'
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :topics
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
   before_action :authenticate_user!
  
  def search
    
    @friends = []
    @plans =[]
    @range = params[:range]

    if @range == "friend"
      @friends = current_user.friends.search(params[:word])
    elsif @range == "plan"
      # @books = Plan.looks(params[:search], params[:word])
      @plans = current_user.plans.search(params[:word],params[:status])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<div class="container">
  <div class="row my-4">
    <h2 class="col-lg-3 mb-5 offset-3">検索結果一覧</h2>
  </div>
  
  <div class="row my-3">
    <div class="col-lg-5 offset-3">
      <table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
        <tbody>
          <% @friends.each do |friend| %>
            <tr>
              <%# binding.pry %>
             　<%#= link_to friend_path(friend) do %>
                <td><%= link_to friend.nickname, friend_path(friend.id) %></td>
              <%#end %>
            </tr>
          <% end %>
          
          <% @plans.each do |plan| %>
          <tr>
            <td><%= link_to plan.title, plan_path(plan.id) %></td>
          </tr>
          <% end %>
        </tbody>
    </table>
    </div>
  </div>
</div>