config/routes.rb
Rails.application.routes.draw do
  
  root to: 'public/homes#top'
  get "search" => "searches#search"
  devise_for :admins, skip: [:registrations, :passwords]  ,controllers: {
    sessions: "admin/sessions"
  }

  #get 'maps/index'
  #root to: 'maps#index'
  #resources :maps, only: [:index]

#  devise_for :users,skip: [:passwords], controllers: {
#    registrations: "public/registrations",
#    sessions: "public/sessions"
#  }
  devise_for :users, skip: [:registrations, :passwords], controllers: {
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in', as:'guest_sign_in'
    get '/users/sign_up' => 'public/registrations#new', as: 'new_user_registration'
    post '/users' => 'public/registrations#create', as: 'user_registration'
  end

  scope module: :public do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :friends
    resources :plans
    get 'users/my_page' => 'users#show'
    get 'users/edit' => 'users#edit'
    get 'users/confirm' => 'users#confirm'
    patch 'users/info' => 'users#update'
    patch 'users/quit' => 'users#quit'
    get 'plans/:id/get' => 'plans#plan_get'
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :topics
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <div class="content">
      <div class="row">
          <title class="col-lg-5">ForeverMyFriends</title>
      </div>
          <meta name="viewport" content="width=device-width,initial-scale=1">
          <%= csrf_meta_tags %>
          <%= csp_meta_tag %>
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=M+PLUS+2:wght@700&family=M+PLUS+Rounded+1c:wght@700&family=Yellowtail&display=swap" rel="stylesheet">
      
          <script src="https://kit.fontawesome.com/cb478adb7c.js" crossorigin="anonymous"></script>
          <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
          <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>

    </div>
   
  </head>

  <body>
    <div class="wrapper">
     <header class="bg-secondary text-white page-header">
      <div class="container">
      <% if user_signed_in? %>
        <div class="row">
          <div class="col-sm-3">
            <%= link_to "Forever My Friends", root_path, class: "logo" %>
          </div>
          <div class="col-sm-4 offset-1">ようこそ、<%= current_user.last_name %>さん！</div>
          <div class="col-sm-4 md-4">
            <div class="search-form">
              <%= form_with url: search_path, local: true, method: :get do |f| %>
              <%= f.text_field :word %>
              <%= f.select :range, options_for_select([['フレンド検索', "friend"], ['スケジュール検索', "plan"]]) %>
              <%= f.select :status, [['進行状況選択してください', nil]] + Plan.statuses.keys.map {|k| [I18n.t("enums.plan.status.#{k}"), k]} %>
              <%= f.submit "検索", class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
     　　 </div>
     　　    <% elsif admin_signed_in? %>
         <div class="row">
           <div class="col-sm-4">
            <%= link_to "Forever My Friends", root_path, class: "logo" %>
           </div>
         </div>
            <% else %>
         <div class="row">
           <div class="col-sm-4">
             <%= link_to "Forever My Friends", root_path, class: "logo" %>
           </div>
          </div>
            <% end %>
    　</div>

     </header>
          <main class="page-body"><%= yield %></main>
     <footer class="bg-secondary text-white page-footer">
      <% if user_signed_in? %>
      <div class="container">
        <div class="row">
          <div class="col-sm-2 offset-1"><%= link_to "My情報", users_my_page_path, class: "btn btn-secondary" %></div>
          <div class="col-sm-2"><%= link_to "フレンドリスト", friends_path, class: "btn btn-secondary" %></div>
          <div class="col-sm-2"><%= link_to "友人カテゴリ", genres_path, class: "btn btn-secondary"  %></div>
          <div class="col-sm-2"><%= link_to "スケジュール",  plans_path, class: "btn btn-secondary"  %></div>
          <div class="col-sm-2"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-secondary"  %></div>
        </div>
      <% elsif admin_signed_in? %>
        <div class="row">
          <div class="col-md-7"></div>
          <div class="col-md-2"><%= link_to "トピック管理", admin_topics_path, class: "btn btn-secondary" %></div>
          <div class="col-md-2"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-secondary" %></div>
          <div class="col-md-1"></div>
        </div>
      <% else %>
        <div class="row">
          <div class=col-md-7></div>
          <div class="col-md-2"><%= link_to "新規登録", new_user_registration_path, class: "btn btn-secondary" %></div>
          <div class="col-md-2"><%= link_to "ログイン", new_user_session_path, class: "btn btn-secondary" %></div>
        </div>
      <% end %>
      </div>
   </footer>
    </div>
  </body>
</html>